<script setup>
</script>
<template>
  <div>
    <h5 class="text-2xl font-normal leading-normal mt-0 mb-2 text-blue-800">
      Pagination
    </h5>
    <div class="py-2">
      <nav class="block">
        <ul class="flex pl-0 rounded list-none flex-wrap">
          <li>
            <a
              href="#pablo"
              class="
                first:ml-0
                text-xs
                font-semibold
                flex
                w-8
                h-8
                mx-1
                p-0
                rounded-full
                items-center
                justify-center
                leading-tight
                relative
                border border-solid border-emerald-500
                bg-white
                text-emerald-500
              "
            >
              <i class="fas fa-chevron-left -ml-px"></i>
              <i class="fas fa-chevron-left -ml-px"></i>
            </a>
          </li>
          <li>
            <a
              href="#pablo"
              class="
                first:ml-0
                text-xs
                font-semibold
                flex
                w-8
                h-8
                mx-1
                p-0
                rounded-full
                items-center
                justify-center
                leading-tight
                relative
                border border-solid border-emerald-500
                bg-white
                text-emerald-500
              "
            >
              <i class="fas fa-chevron-left -ml-px"></i>
            </a>
          </li>
          <li>
            <a
              href="#pablo"
              class="
                first:ml-0
                text-xs
                font-semibold
                flex
                w-8
                h-8
                mx-1
                p-0
                rounded-full
                items-center
                justify-center
                leading-tight
                relative
                border border-solid border-emerald-500
                bg-white
                text-emerald-500
              "
            >
              1
            </a>
          </li>
          <li>
            <a
              href="#pablo"
              class="
                first:ml-0
                text-xs
                font-semibold
                flex
                w-8
                h-8
                mx-1
                p-0
                rounded-full
                items-center
                justify-center
                leading-tight
                relative
                border border-solid border-emerald-500
                bg-white
                text-emerald-500
              "
            >
              2
            </a>
          </li>
          <li>
            <a
              href="#pablo"
              class="
                first:ml-0
                text-xs
                font-semibold
                flex
                w-8
                h-8
                mx-1
                p-0
                rounded-full
                items-center
                justify-center
                leading-tight
                relative
                border border-solid border-emerald-500
                bg-white
                text-emerald-500
              "
            >
              3
            </a>
          </li>
          <li>
            <a
              href="#pablo"
              class="
                first:ml-0
                text-xs
                font-semibold
                flex
                w-8
                h-8
                mx-1
                p-0
                rounded-full
                items-center
                justify-center
                leading-tight
                relative
                border border-solid border-emerald-500
                bg-white
                text-emerald-500
              "
            >
              4
            </a>
          </li>
          <li>
            <a
              href="#pablo"
              class="
                first:ml-0
                text-xs
                font-semibold
                flex
                w-8
                h-8
                mx-1
                p-0
                rounded-full
                items-center
                justify-center
                leading-tight
                relative
                border border-solid border-emerald-500
                bg-white
                text-emerald-500
              "
            >
              5
            </a>
          </li>
          <li>
            <a
              href="#pablo"
              class="
                first:ml-0
                text-xs
                font-semibold
                flex
                w-8
                h-8
                mx-1
                p-0
                rounded-full
                items-center
                justify-center
                leading-tight
                relative
                border border-solid border-emerald-500
                bg-white
                text-emerald-500
              "
            >
              <i class="fas fa-chevron-right -mr-px"></i>
            </a>
          </li>
          <li>
            <a
              href="#pablo"
              class="
                first:ml-0
                text-xs
                font-semibold
                flex
                w-8
                h-8
                mx-1
                p-0
                rounded-full
                items-center
                justify-center
                leading-tight
                relative
                border border-solid border-emerald-500
                bg-white
                text-emerald-500
              "
            >
              <i class="fas fa-chevron-right -mr-px"></i>
              <i class="fas fa-chevron-right -mr-px"></i>
            </a>
          </li>
        </ul>
      </nav>
    </div>
  </div>
</template>