<script setup>
</script>
<template>
  <div>
    <h5 class="text-2xl font-normal leading-normal mt-0 mb-2 text-blue-800">
      Button
    </h5>
    <button
      class="
        text-emerald-500
        background-transparent
        font-bold
        uppercase
        px-8
        py-3
        outline-none
        focus:outline-none
        mr-1
        mb-1
        ease-linear
        transition-all
        duration-150
      "
      type="button"
    >
      <i class="fas fa-home"></i>
    </button>
    <button
      class="
        text-emerald-500
        bg-transparent
        border border-solid border-emerald-500
        hover:bg-emerald-500 hover:text-white
        active:bg-emerald-600
        font-bold
        uppercase
        text-xs
        px-4
        py-2
        rounded-full
        outline-none
        focus:outline-none
        mr-1
        mb-1
        ease-linear
        transition-all
        duration-150
      "
      type="button"
    >
      Small
    </button>
    <button
      class="
        text-emerald-500
        bg-transparent
        border border-solid border-emerald-500
        hover:bg-emerald-500 hover:text-white
        active:bg-emerald-600
        font-bold
        uppercase
        text-sm
        px-6
        py-3
        rounded-full
        outline-none
        focus:outline-none
        mr-1
        mb-1
        ease-linear
        transition-all
        duration-150
      "
      type="button"
    >
      Regular
    </button>
    <button
      class="
        text-emerald-500
        bg-transparent
        border border-solid border-emerald-500
        hover:bg-emerald-500 hover:text-white
        active:bg-emerald-600
        font-bold
        uppercase
        px-8
        py-3
        rounded-full
        outline-none
        focus:outline-none
        mr-1
        mb-1
        ease-linear
        transition-all
        duration-150
      "
      type="button"
    >
      Large
    </button>
    <button
      class="
        bg-emerald-500
        text-white
        active:bg-emerald-600
        font-bold
        uppercase
        text-xs
        px-4
        py-2
        rounded-full
        shadow
        hover:shadow-md
        outline-none
        focus:outline-none
        mr-1
        mb-1
        ease-linear
        transition-all
        duration-150
      "
      type="button"
    >
      Small
    </button>
  </div>
</template>